### ISSUE TITLE
Allow to download this library from NPM

### ISSUE THREAD

**Issue by tkowalczyk** [starterra/starterra-tool-dapp#1]
> As a developer I want to be able to download the library from the npm repository

**Comment by tkowalczyk** [comment]
we will close this after publishing package to npm. For now we have [workflow ](https://github.com/starterra/starterra-tool-dapp/blob/main/.github/workflows/npm-publish.yml) for it.

**Comment by nocmar** [comment]
https://www.npmjs.com/package/@starterra/starterra-tool-dapp

**Comment by nocmar** [comment]
avaliable at https://www.npmjs.com/package/@starterra/starterra-tool-dapp
