### ISSUE TITLE
Fork  "@terra-money/wallet-provider" when package will be extracted from anchor app

### ISSUE THREAD

**Issue by nocmar** [starterra/starterra-tool-dapp#14]
As I developer I would like to fork @terra-money/wallet-provider I would like to fork the library and extend it with the UI control  instead of using it as dependency. Since currently it is impossible to do that because  @terra-money/wallet-provider is inside anchor protocol we need to wait to do that

**Comment by nocmar** [comment]
We will use wallet-provider as dependency, it is easier to just update a version in package.json instead of merge source code

**Comment by tkowalczyk** [comment]
yeah definietyl, good choice
