### ISSUE TITLE
Allow to use `@terra-money/wallet-provider`

### ISSUE THREAD

**Issue by tkowalczyk** [starterra/starterra-tool-dapp#2]
> As a programmer, I want to be able to use resources inside the library [@terra-money/wallet-provider](https://www.npmjs.com/package/@terra-money/wallet-provider)

**Comment by nocmar** [comment]
All resources from wallet-provider are accessible inside our library, for example
import { useWallet, useConnectedWallet } from 'starterra-tool-dapp'
