### ISSUE TITLE
Test for token transfer to external account address as well as contract address

### ISSUE THREAD

**Issue by tkowalczyk** [starterra/starterra-tool-dapp#25]
We have to be sure that our solution allows to send tokens to external account (managed by private key) as well as to smart contract address.

**Comment by nocmar** [comment]
Test for sending tokens back to airdrop sc 
https://finder.terra.money/tequila-0004/tx/AB8EDB463DC586022DC7D6BF282AF2D96A256379B5D1182ECE40B4DE5535E12F
