### ISSUE TITLE
Token transfer for cw20 tokens doesn't work 

### ISSUE THREAD

**Issue by nocmar** [starterra/starterra-tool-dapp#31]
For cw20 tokens transfer there is an error "failed to parse to Coin"

**Comment by michalkurdziel** [comment]
@nocmar can you put some screenshot of the error?

**Comment by tkowalczyk** [comment]
I think it is already solved? Marta?

**Comment by nocmar** [comment]
Yes it is solved, waiting for PR approval. @michalkurdziel do you  screenshot?

**Comment by tkowalczyk** [comment]
Fixed by https://github.com/starterra/starterra-tool-dapp/pull/32, I think we can close now and prepare for test.
