### ISSUE TITLE
Validate amount with proper precision 

### ISSUE THREAD

**Issue by nocmar** [starterra/starterra-tool-dapp#33]
Current validation precision is not enough. Send form should not allow to send below transaction. It should be blocked on Amount validation level. Also the max amount button will be useful. 
 
_**___execute wasm contract failed: underflow: 999985 - 1000000: failed to execute message; message index: 0_**_

https://finder.terra.money/tequila-0004/tx/B1DBD3D983C6788C6A0B4D9483F085CBB0B4DF78DB0EAC85F25355D964605166__

**Comment by tkowalczyk** [comment]
so this case is only related to input validation? or there is smth buggy in logic flow?

**Comment by nocmar** [comment]
For sure I need to fix the validation, since I display balance with precision 4 the same was used for validation. I'm not sure how about logic, I decided to use BigNumber and div/pow operation but I noticed recently that there are some special types Int and Dec in terra.js and maybe we should use them instead  new Int(new Dec(amount).mul(1000000)).toString(), but it require some investigation.

**Comment by nocmar** [comment]
fixed in v0.1.5
