### ISSUE TITLE
Allow to extend UI components

### ISSUE THREAD

**Issue by tkowalczyk** [starterra/starterra-tool-dapp#8]
> As a developer, I want to be able to extend/expand the UI components listed in https://github.com/starterra/starterra-tool-dapp/issues/6 according to styles appropriate to the project currently being developed

**Comment by tkowalczyk** [comment]
@nocmar & @Mskalba how we are going to achieve this task?

**Comment by nocmar** [comment]
We discussed today that user should be able to provide own material ui class with style to be able to override our custom styles. I need to do same changes, so let's leave is as open

**Comment by tkowalczyk** [comment]
alright :)

**Comment by nocmar** [comment]
Already merged to develop
